/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 01e25533b34e8f167bb2c8d2e3fe1333)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	READ_ONLY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "READ_ONLY">> {}
}
